# Netlify Deployment Ayarları

## Build Settings
```toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

## Environment Variables (Netlify Site Settings'e ekle)
```
VITE_SUPABASE_URL=https://gvupbilsfysmihcyhmjc.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2dXBiaWxzZnlzbWloY3lobWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDc1MjQsImV4cCI6MjA2OTAyMzUyNH0.BSw-lMUMTr9RikunkybeRmU0EJPEHQfG9jC2EQ03H9w
VITE_APP_URL=https://oguzyolyapan.netlify.app
VITE_APP_NAME=Oğuz Yolyapan
```
